[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_ENV = "production"

[context.production.environment]
  # Add any production-specific environment variables here