[build]
  command = "npm install --production=false && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  # Disable automatic devDependencies exclusion
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--production=false"