[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"  # Updated to match package requirements
  NODE_ENV = "production"

[context.production.environment]
  # Production-specific environment variables here